# Generated by Django 5.0 on 2024-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_danhmuc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='danhmuc',
            field=models.ManyToManyField(related_name='product', to='app.danhmuc'),
        ),
    ]
