# Generated by Django 5.0 on 2024-11-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_danhmuc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='danhmuc',
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sub_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu_s', to='app.menu')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ManyToManyField(related_name='product', to='app.menu'),
        ),
        migrations.DeleteModel(
            name='DanhMuc',
        ),
    ]
