# Generated by Django 5.0 on 2024-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_product_danhmuc_menu_product_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chitiet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
