# Generated by Django 5.0 on 2024-11-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_chitiet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
