# Generated by Django 5.0 on 2024-11-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer',
            new_name='hangsx',
        ),
    ]
