# Generated by Django 5.0 on 2024-11-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_manufacturer_product_hangsx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow')], max_length=20, null=True),
        ),
    ]
