# Generated by Django 5.0 on 2024-11-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
