# Generated by Django 5.0 on 2024-12-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dung_luong',
            field=models.CharField(blank=True, choices=[('small', 'Small (1GB)'), ('medium', 'Medium (5GB)'), ('large', 'Large (10GB)'), ('extra_large', 'Extra Large (50GB)')], max_length=20, null=True),
        ),
    ]
