# Generated by Django 5.0 on 2024-12-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_storage_product_dung_luong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dung_luong',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
