# Generated by Django 5.0 on 2024-12-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_size_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
