# Generated by Django 5.0 on 2024-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dungluong1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dungluong2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
