# Generated by Django 5.0.6 on 2024-12-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
